services:
  yarg-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://yarg-aggregator-mongo-1:27017/yarg_db
      - NEXT_PUBLIC_APP_URL=http://yarg-aggregator.7212.qzz.io:3000
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - yarg-network
      - tunnel

  mongo:
    image: mongodb-raspberrypi4-unofficial-r7.0.4:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - yarg-network

volumes:
  mongo_data:

networks:
  yarg-network:
    driver: bridge
  tunnel:
    external: true
